[package]
name = "advent4b"
version = "0.1.0"
authors = ["John Batty <john.batty@metaswitch.com>"]
edition = "2018"
publish = ["metaswitch"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.6"
itertools = "0.8.2"
